### ISSUE TITLE
Wrong header in test/*.spec.js files

### ISSUE THREAD

**Issue by dandelionsam** [corradodiba/unict#4]
Change these lines:
```
const expect = require('mocha');
const chai = require('chai');
const chaiHttp = require('chai-http');
```

to these:
```
const chai = require('chai');
const chaiHttp = require('chai-http');
const expect = chai.expect;
```

**Comment by davideturzo** [comment]
Io, in qualità di presidente, mi sono sporcato le mani e, naturalmente, ho risolto il problema su `tweets.spec.js`

**Comment by dandelionsam** [comment]
Io altrettanto ho risolto il problema su `index.spec.js`

**Comment by corradodiba** [comment]
anche @GlitchXCIV ha risolto il problema in `users.spec.js`, pertanto provvedo a chiudere la issue.
